// Parents crossed on more than one row (docs/plans/2026-09-29-backcross-design.md).
// A genotype that is a parent in crosses on two rows can be drawn on only
// one of them (a backcross to a parent, a stock reused in a later
// generation). It keeps its crosses on the smallest row index (topmost); each of
// its other crosses gets its own copy of it, a founder with a fresh
// genotypeId and no `parents`, and uses the copy: that cross's x glyph's and
// offspring's `parents` are rewired. (Copies are unlinked, so two crosses
// never share one; to share, cross with an existing copy.) Only crosses
// with an offspring and both parents in `lineage` count. A cross's row is
// the larger top-down depth of its two parents, so a cross never needs
// copies of both.
//
// With `subset` (subset mode), conflicts are still found over the whole
// `lineage`, but only crosses inside `subset` (both parents and every
// offspring in it) get copies; the rest are not the subset's business and
// are left alone. Each copy joins `subset`, and a genotype that got a copy
// leaves it if it is no longer a parent of a cross whose two parents are
// both in the subset (the main Tidy sweep redraws any x glyph on those
// terms alone, regardless of offspring) nor an offspring of a cross inside
// the subset (it was there only as the moved cross's mate), so it stays
// where it is. `subset` is mutated in place, as the script does.
//
// Returns null if nothing needed splitting.

import { topDownDepths } from "../scene/graph";
import type { Parents, SceneElement } from "../schema";

export interface MultiRowPlan {
  copies: string[];
  added: SceneElement[];
  patches: Map<string, Partial<SceneElement>>;
}

interface Cross {
  parents: Parents;
  row: number;
  offspring: Set<string>;
}

// Elements copied for a moved genotype: alleles, fractions, separators,
// glyph and label with new element ids in one new group. Frames and label
// boxes are regenerated by Tidy.
const COPIED_KINDS = new Set(["genotype-allele", "genotype-fraction", "genotype-separator", "genotype-glyph", "genotype-label"]);

export function planMultiRowSplit(
  all: readonly SceneElement[],
  lineage: ReadonlySet<string>,
  subset: Set<string> | null,
  newId: () => string = () => crypto.randomUUID(),
): MultiRowPlan | null {
  const topDown = topDownDepths(lineage, all);
  const crosses = new Map<string, Cross>();
  for (const el of all) {
    const p = el.customData?.parents;
    if (!el.customData?.genotypeId || !p?.maternal || !p?.paternal) continue;
    if (!lineage.has(p.maternal) || !lineage.has(p.paternal)) continue;
    const key = `${p.maternal}|${p.paternal}`;
    let c = crosses.get(key);
    if (!c) {
      c = { parents: p, row: Math.max(topDown.get(p.maternal) ?? 0, topDown.get(p.paternal) ?? 0), offspring: new Set() };
      crosses.set(key, c);
    }
    c.offspring.add(el.customData.genotypeId);
  }

  // A cross inside the subset: both parents and every offspring in it.
  const inSubset = (c: Cross): boolean =>
    !subset || (subset.has(c.parents.maternal) && subset.has(c.parents.paternal) && [...c.offspring].every((g) => subset!.has(g)));
  // A cross whose two parents (offspring aside) are both in the subset. The
  // main Tidy sweep redraws any x glyph on those terms alone, so this (not
  // `inSubset`) is what decides whether a genotype still has an unswapped
  // cross drawn inside the subset.
  const parentsInSubset = (c: Cross): boolean => !subset || (subset.has(c.parents.maternal) && subset.has(c.parents.paternal));

  const swap = new Map<string, { maternal?: string; paternal?: string }>();
  const copyOf = new Map<string, string>(); // copy genotypeId -> original genotypeId
  for (const gid of lineage) {
    const mine = [...crosses].filter(([, c]) => c.parents.maternal === gid || c.parents.paternal === gid);
    const top = Math.min(...mine.map(([, c]) => c.row));
    for (const [key, c] of mine) {
      if (c.row === top || !inSubset(c)) continue;
      const copy = newId();
      copyOf.set(copy, gid);
      let s = swap.get(key);
      if (!s) swap.set(key, (s = {}));
      if (c.parents.maternal === gid) s.maternal = copy;
      if (c.parents.paternal === gid) s.paternal = copy;
    }
  }
  if (!copyOf.size) return null;

  if (subset) {
    for (const [copy, gid] of copyOf) {
      subset.add(copy);
      if (!subset.has(gid)) continue;
      const parentHere = [...crosses].some(
        ([key, c]) =>
          parentsInSubset(c) &&
          ((c.parents.maternal === gid && !swap.get(key)?.maternal) || (c.parents.paternal === gid && !swap.get(key)?.paternal)),
      );
      const offspringHere = [...crosses.values()].some((c) => c.offspring.has(gid) && inSubset(c));
      if (!parentHere && !offspringHere) subset.delete(gid);
    }
  }

  const added: SceneElement[] = [];
  for (const [copy, gid] of copyOf) {
    const group = newId();
    for (const el of all) {
      if (el.customData?.genotypeId !== gid || !COPIED_KINDS.has(el.customData.kind ?? "")) continue;
      const { parents, ...rest } = el.customData;
      const c: SceneElement = structuredClone(el);
      c.id = newId();
      c.groupIds = [group];
      c.boundElements = [];
      c.containerId = null;
      c.customData = { ...rest, genotypeId: copy };
      added.push(c);
    }
  }

  const patches = new Map<string, Partial<SceneElement>>();
  for (const el of all) {
    const p = el.customData?.parents;
    const s = p && swap.get(`${p.maternal}|${p.paternal}`);
    if (!s || !(el.customData?.genotypeId || el.customData?.kind === "cross-glyph")) continue;
    patches.set(el.id, {
      customData: { ...el.customData, parents: { maternal: s.maternal ?? p.maternal, paternal: s.paternal ?? p.paternal } },
    });
  }

  return { copies: [...copyOf.keys()], added, patches };
}
