import { describe, expect, it } from "vitest";
import { planMultiRowSplit } from "../../src/backcross/plan";
import type { Parents, SceneElement } from "../../src/schema";

const counter = () => { let n = 0; return () => `new-${++n}`; };
let seq = 0;
const allele = (g: string, parents?: Parents): SceneElement => ({
  id: `e${++seq}`, type: "text", x: 0, y: 0, width: 10, height: 10, groupIds: [`grp-${g}`], boundElements: [],
  text: "w", customData: { schemaVersion: 2, kind: "genotype-allele", genotypeId: g, chromosome: "X", side: "top", ...(parents ? { parents } : {}) },
});
const frame = (g: string): SceneElement => ({ ...allele(g), type: "rectangle", customData: { schemaVersion: 2, kind: "genotype-frame", genotypeId: g } });
const glyph = (m: string, p: string): SceneElement => ({ id: `x-${m}-${p}`, type: "text", x: 0, y: 0, width: 10, height: 10, customData: { schemaVersion: 2, kind: "cross-glyph", parents: { maternal: m, paternal: p } } });
// A member element of a genotype's drawing, with an explicit kind and bound
// furniture, for the "copy contents" test: originals carry a non-empty
// boundElements and a containerId so a copy that forgot to reset them would
// be caught.
const member = (g: string, kind: string, extra: Record<string, unknown> = {}): SceneElement => ({
  id: `m-${g}-${kind}-${++seq}`, type: "text", x: 0, y: 0, width: 10, height: 10,
  groupIds: ["orig-group"], boundElements: [{ id: `bound-${seq}`, type: "text" }], containerId: "orig-container",
  customData: { schemaVersion: 2, kind, genotypeId: g, ...extra },
});

// P1 x P2 -> A; A x P2 -> B (a backcross to the father).
const scene = () => [allele("P1"), allele("P2"), frame("P2"), allele("A", { maternal: "P1", paternal: "P2" }), glyph("P1", "P2"),
  allele("B", { maternal: "A", paternal: "P2" }), glyph("A", "P2")];

describe("planMultiRowSplit", () => {
  it("copies a parent crossed on two rows for the lower cross", () => {
    const all = scene();
    const plan = planMultiRowSplit(all, new Set(["P1", "P2", "A", "B"]), null, counter())!;
    expect(plan.copies).toEqual(["new-1"]);
    const copyEls = plan.added.filter((e) => e.customData?.genotypeId === "new-1");
    expect(copyEls.map((e) => e.customData?.kind)).toEqual(["genotype-allele"]); // frames are regenerated by Tidy
    expect(copyEls[0].customData?.parents).toBeUndefined();
    expect(copyEls[0].boundElements).toEqual([]);
    const b = all.find((e) => e.customData?.genotypeId === "B")!;
    expect(plan.patches.get(b.id)?.customData?.parents).toEqual({ maternal: "A", paternal: "new-1" });
    expect(plan.patches.get("x-A-P2")?.customData?.parents).toEqual({ maternal: "A", paternal: "new-1" });
    expect(plan.patches.has("x-P1-P2")).toBe(false);
  });
  it("does nothing when every parent is used on one row", () => {
    expect(planMultiRowSplit(scene().slice(0, 5), new Set(["P1", "P2", "A"]), null, counter())).toBe(null);
  });
  it("subset mode: the copy joins the subset, the original leaves it", () => {
    const subset = new Set(["A", "P2", "B"]);
    planMultiRowSplit(scene(), new Set(["P1", "P2", "A", "B"]), subset, counter());
    expect([...subset].sort()).toEqual(["A", "B", "new-1"]);
  });

  // Rule: rows come from top-down depths, and a genotype keeps its crosses
  // on the SMALLEST row (not the largest, not the first-seen). S is a
  // founder crossed at three different rows (via A, then C, then E, each
  // one generation deeper): row 1 (S x A) is kept unswapped; rows 2 and 3
  // each get their own copy of S.
  it("keeps the smallest-row cross and copies every deeper one", () => {
    const all = [
      allele("P1"), allele("P2"),
      allele("A", { maternal: "P1", paternal: "P2" }), // topDown 1
      allele("P3"),
      allele("C", { maternal: "A", paternal: "P3" }), // topDown 2
      allele("P4"),
      allele("E", { maternal: "C", paternal: "P4" }), // topDown 3
      allele("S"),
      allele("D1", { maternal: "S", paternal: "A" }), // row 1: kept
      allele("D2", { maternal: "S", paternal: "C" }), // row 2: copy
      allele("D3", { maternal: "S", paternal: "E" }), // row 3: copy
    ];
    const lineage = new Set(["P1", "P2", "A", "P3", "C", "P4", "E", "S", "D1", "D2", "D3"]);
    const plan = planMultiRowSplit(all, lineage, null, counter())!;
    expect(plan.copies.length).toBe(2);
    expect(new Set(plan.copies).size).toBe(2); // never shared between the two deeper crosses
    const d1 = all.find((e) => e.customData?.genotypeId === "D1")!;
    const d2 = all.find((e) => e.customData?.genotypeId === "D2")!;
    const d3 = all.find((e) => e.customData?.genotypeId === "D3")!;
    expect(plan.patches.has(d1.id)).toBe(false); // row 1, the smallest, stays on S
    expect(plan.patches.get(d2.id)?.customData?.parents?.maternal).toBe(plan.copies[0]);
    expect(plan.patches.get(d3.id)?.customData?.parents?.maternal).toBe(plan.copies[1]);
  });

  // Rule: one copy per lower cross, never shared, even when two lower
  // crosses land on the SAME row. Two F1 sisters (A and C, both children of
  // P1 x P2) are each crossed back to P2; each backcross gets its own copy
  // of P2, not one copy reused for both.
  it("two sisters crossed to the same parent each get their own copy", () => {
    const all = [
      allele("P1"), allele("P2"),
      allele("A", { maternal: "P1", paternal: "P2" }),
      allele("C", { maternal: "P1", paternal: "P2" }),
      allele("B", { maternal: "A", paternal: "P2" }),
      allele("D", { maternal: "C", paternal: "P2" }),
    ];
    const lineage = new Set(["P1", "P2", "A", "C", "B", "D"]);
    const plan = planMultiRowSplit(all, lineage, null, counter())!;
    expect(plan.copies.length).toBe(2);
    const b = all.find((e) => e.customData?.genotypeId === "B")!;
    const d = all.find((e) => e.customData?.genotypeId === "D")!;
    const bCopy = plan.patches.get(b.id)?.customData?.parents?.paternal;
    const dCopy = plan.patches.get(d.id)?.customData?.parents?.paternal;
    expect(bCopy).not.toBe(dCopy);
    expect([bCopy, dCopy].sort()).toEqual([...plan.copies].sort());
  });

  // Rule: subset gating uses parentsInSubset (both parents in the subset,
  // offspring aside), not inSubset (which also requires every offspring),
  // to decide whether a genotype still has an unswapped cross drawn inside
  // the subset. P1 x P2 -> A, C. A x P2 -> B (swapped: B is in the
  // subset). C x P2 -> D, but D is NOT in the subset, so that cross is not
  // eligible for a copy (left alone) even though both of its parents (C,
  // P2) are in the subset. P2 must stay in the subset: the unswapped C x P2
  // cross still has both parents in it.
  it("subset gating: a genotype stays if an unswapped cross's parents are both in the subset", () => {
    const all = [
      allele("P1"), allele("P2"),
      allele("A", { maternal: "P1", paternal: "P2" }),
      allele("C", { maternal: "P1", paternal: "P2" }),
      allele("B", { maternal: "A", paternal: "P2" }),
      allele("D", { maternal: "C", paternal: "P2" }),
    ];
    const lineage = new Set(["P1", "P2", "A", "C", "B", "D"]);
    const subset = new Set(["A", "C", "P2", "B"]); // D excluded
    const plan = planMultiRowSplit(all, lineage, subset, counter())!;
    expect(plan.copies.length).toBe(1); // only A x P2 (fully in the subset) is copied
    expect(subset.has("P2")).toBe(true);
    expect(subset.has(plan.copies[0])).toBe(true);
    expect(subset.has("D")).toBe(false);
  });

  // Rule: every element of a moved cross's offspring is rewired, not just
  // one (a genotype's `parents` is denormalized across its members).
  it("rewires every element of the offspring, not just the first", () => {
    const all = [
      allele("P1"), allele("P2"),
      allele("A", { maternal: "P1", paternal: "P2" }),
      allele("B", { maternal: "A", paternal: "P2" }),
      allele("B", { maternal: "A", paternal: "P2" }), // a second tagged element of B
    ];
    const lineage = new Set(["P1", "P2", "A", "B"]);
    const plan = planMultiRowSplit(all, lineage, null, counter())!;
    const bEls = all.filter((e) => e.customData?.genotypeId === "B");
    expect(bEls.length).toBe(2);
    for (const el of bEls) {
      expect(plan.patches.get(el.id)?.customData?.parents).toEqual({ maternal: "A", paternal: plan.copies[0] });
    }
  });

  // Rule: copy contents. The copied genotype (A) is itself not a founder
  // (it has its own `parents`, {P1, P2}); the copy must still drop them (a
  // fresh founder), and only the copyable kinds (allele here; frame is
  // excluded, regenerated by Tidy) are copied, each with a fresh id.
  it("copy contents: strips the original's own parents and skips uncopyable kinds", () => {
    const all = [
      allele("P1"), allele("P2"),
      allele("A", { maternal: "P1", paternal: "P2" }),
      frame("A"),
      allele("P3"),
      allele("C", { maternal: "A", paternal: "P3" }), // row 1: kept
      allele("E", { maternal: "C", paternal: "A" }), // row 2: A copied
    ];
    const lineage = new Set(["P1", "P2", "A", "P3", "C", "E"]);
    const plan = planMultiRowSplit(all, lineage, null, counter())!;
    expect(plan.copies.length).toBe(1);
    const copyId = plan.copies[0];
    const copyEls = plan.added.filter((e) => e.customData?.genotypeId === copyId);
    expect(copyEls.map((e) => e.customData?.kind)).toEqual(["genotype-allele"]);
    expect(copyEls[0].customData?.parents).toBeUndefined();
    const originalA = all.find((e) => e.customData?.genotypeId === "A" && e.customData?.kind === "genotype-allele")!;
    expect(copyEls[0].id).not.toBe(originalA.id);
  });

  // Rule: subset retention for a NON-founder G (`offspringHere`). G is born
  // of P1 x P2, and is itself a multi-row parent: G x P4 (row 1, kept) and
  // G x P6 (row 2, deeper, copied). P4 and I are deliberately left out of
  // the subset, so G's only unswapped, parents-in-subset cross is nothing
  // (P4 is outside); G can only stay in the subset via `offspringHere`, i.e.
  // its birth cross P1 x P2 -> G being fully inside the subset.
  const nonFounderScene = () => [
    allele("P1"), allele("P2"), // G's birth parents
    allele("P3"), allele("X1"), allele("X2"),
    allele("X3", { maternal: "X1", paternal: "X2" }), // topDown 1
    allele("P6", { maternal: "X3", paternal: "P3" }), // topDown 2
    allele("P4"), // G's row-1 mate, kept outside the subset
    allele("G", { maternal: "P1", paternal: "P2" }), // topDown 1 (G's birth cross)
    allele("I", { maternal: "G", paternal: "P4" }), // G x P4 -> I, row 1: kept
    allele("J", { maternal: "G", paternal: "P6" }), // G x P6 -> J, row 2: copied
  ];
  const nonFounderLineage = new Set(["P1", "P2", "P3", "X1", "X2", "X3", "P6", "P4", "G", "I", "J"]);

  it("subset gating: a non-founder G stays when its own birth cross is fully in the subset", () => {
    const subset = new Set(["P1", "P2", "G", "P6", "J"]); // P4, I left out; birth cross P1|P2->G fully in
    const plan = planMultiRowSplit(nonFounderScene(), nonFounderLineage, subset, counter())!;
    expect(plan.copies.length).toBe(1); // only G x P6 is copied
    expect(subset.has("G")).toBe(true);
  });

  it("subset gating: a non-founder G leaves when its birth cross has a parent outside the subset", () => {
    const subset = new Set(["P1", "G", "P6", "J"]); // P2 (a birth parent) left out this time
    const plan = planMultiRowSplit(nonFounderScene(), nonFounderLineage, subset, counter())!;
    expect(plan.copies.length).toBe(1); // still one copy: G x P6
    expect(subset.has("G")).toBe(false);
  });

  // Rule: copy contents are complete. G2 is copied for the A x G2 -> B
  // cross; its drawing has one of every copyable kind (allele, fraction,
  // separator, glyph, label) plus a frame and a label-box, which must NOT
  // be copied. Every original member carries a non-empty boundElements and
  // a containerId, so a copy that forgot to reset them is caught; all
  // originals share one group ("orig-group"), so a copy that kept it
  // instead of a fresh one is caught too.
  it("copy contents: copies every copyable kind once, in a fresh group, with bindings and container reset", () => {
    const g2 = [
      member("G2", "genotype-allele", { chromosome: "X", side: "top" }),
      member("G2", "genotype-fraction", { chromosome: "II" }),
      member("G2", "genotype-separator", { after: "X" }),
      member("G2", "genotype-glyph"),
      member("G2", "genotype-label"),
      member("G2", "genotype-frame"), // not copied
      member("G2", "genotype-label-box"), // not copied
    ];
    const all = [allele("P1"), ...g2, allele("A", { maternal: "P1", paternal: "G2" }), allele("B", { maternal: "A", paternal: "G2" })];
    const lineage = new Set(["P1", "G2", "A", "B"]);
    const plan = planMultiRowSplit(all, lineage, null, counter())!;
    expect(plan.copies.length).toBe(1);
    const copyId = plan.copies[0];
    const copyEls = plan.added.filter((e) => e.customData?.genotypeId === copyId);
    expect(copyEls.map((e) => e.customData?.kind).sort()).toEqual([
      "genotype-allele", "genotype-fraction", "genotype-glyph", "genotype-label", "genotype-separator",
    ]);
    const group = copyEls[0].groupIds?.[0];
    expect(group).toBeTruthy();
    expect(group).not.toBe("orig-group");
    for (const el of copyEls) {
      expect(el.groupIds).toEqual([group]);
      expect(el.containerId).toBeNull();
      expect(el.boundElements).toEqual([]);
    }
  });

  // Rule: a cross with one parent outside `lineage` is not a cross at all
  // for this pass, however different its (meaningless) row would be. G is a
  // founder crossed once inside the lineage, with a non-founder P_in (row
  // 1), and once with P_out, which is NOT in `lineage`; if that second
  // cross were counted, it would appear to be row 0 (an out-of-lineage
  // parent defaults to depth 0), manufacturing a two-row conflict for G
  // that doesn't exist. Expect no split at all.
  it("ignores a cross whose partner is outside the lineage", () => {
    const all = [
      allele("G"),
      allele("X"), allele("Y"),
      allele("P_in", { maternal: "X", paternal: "Y" }), // topDown 1
      allele("D", { maternal: "G", paternal: "P_in" }), // the only real cross for G, row 1
      allele("P_out"), // not in lineage
      allele("C", { maternal: "G", paternal: "P_out" }), // a cross outside the lineage: must be ignored
    ];
    const lineage = new Set(["G", "X", "Y", "P_in", "D"]);
    expect(planMultiRowSplit(all, lineage, null, counter())).toBe(null);
  });
});
